-- MySQL Script generated by MySQL Workbench
-- Sat May 17 16:56:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema support_ticket_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema support_ticket_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `support_ticket_manager` DEFAULT CHARACTER SET utf8 ;
USE `support_ticket_manager` ;

-- -----------------------------------------------------
-- Table `support_ticket_manager`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`grupo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_grupo_idx` (`grupo_id` ASC),
  CONSTRAINT `fk_usuario_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `support_ticket_manager`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`empresa_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`empresa_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_empresa_usuario_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_empresa_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `support_ticket_manager`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_usuario_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `support_ticket_manager`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  `documento` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(255) NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(255) NULL,
  `responsavel_nome` VARCHAR(255) NOT NULL,
  `responsavel_email` VARCHAR(255) NULL,
  `responsavel_telefone` VARCHAR(14) NOT NULL,
  `responsavel_documento` VARCHAR(11) NOT NULL,
  `cep` INT NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `pais` VARCHAR(255) NULL,
  `endereco` VARCHAR(255) NULL,
  `numero` VARCHAR(50) NULL,
  `bairro` VARCHAR(255) NULL,
  `situacao` TINYINT(1) NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `support_ticket_manager`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`empresa_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`empresa_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_cliente_empresa1_idx` (`empresa_id` ASC),
  INDEX `fk_empresa_cliente_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_empresa_cliente_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `support_ticket_manager`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `support_ticket_manager`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`empresa_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`empresa_servico` (
  `empresa_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `situacao` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_servico_servico1_idx` (`servico_id` ASC),
  INDEX `fk_empresa_servico_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_empresa_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `support_ticket_manager`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_servico_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `support_ticket_manager`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`suporte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `assunto` LONGTEXT NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'ABERTO',
  `situacao` TINYINT(1) NULL,
  `cadastrado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `alterado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_suporte_empresa1_idx` (`empresa_id` ASC),
  INDEX `fk_suporte_servico1_idx` (`servico_id` ASC),
  INDEX `fk_suporte_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_suporte_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `support_ticket_manager`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suporte_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `support_ticket_manager`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suporte_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `support_ticket_manager`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_ticket_manager`.`suporte_mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_ticket_manager`.`suporte_mensagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `suporte_id` INT NOT NULL,
  `mensagem` LONGTEXT NOT NULL,
  `proprietario` VARCHAR(255) NULL,
  `respondido` TINYINT(1) NOT NULL,
  `cadastrado` TIMESTAMP NULL,
  `alterado` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suporte_mensagem_suporte1_idx` (`suporte_id` ASC),
  CONSTRAINT `fk_suporte_mensagem_suporte1`
    FOREIGN KEY (`suporte_id`)
    REFERENCES `support_ticket_manager`.`suporte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
